version: '3'
services:
  nginx:
    image: nginx:latest
    container_name: nginx
    volumes:
      - ~/nginx.conf:/etc/nginx/nginx.conf
      - /etc/letsencrypt/:/etc/letsencrypt/
    ports:
      - 80:80
      - 443:443

  app:
    image: evanturner/playoff-contention:latest
    container_name: app

  app-beta:
    image: evanturner/playoff-contention-beta:latest
    container_name: app-beta
